apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bsdemo
  description: The Spotify web API
  tags:
    - spotify
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml
