apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bsdemo
  description: The Spotify web API
  tags:
    - spotify
    - rest
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://raw.githubusercontent.com/radoslaw-wielonski-nc/backstage-testing/main/swaggersource.json
