apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: backstage test teams
  annotations:
  tags:
    - python
    - package
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
spec:
  type: package
  owner: team-a
  lifecycle: experimental
